### ISSUE TITLE
UI Mockups

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/repEAT#9]
Design wireframes of the UI of the app. Upload results to a Wiki page.

**Comment by pm-retail** [comment]
![Einkaufslisten](https://user-images.githubusercontent.com/67836164/91966357-05c1c280-ed12-11ea-9fd5-4e3864fd94e8.png)
![Haushalt (Profil) pflegen](https://user-images.githubusercontent.com/67836164/91966360-06f2ef80-ed12-11ea-80e9-39a75dcd6d61.png)
![Meal Plan   Bibliothek](https://user-images.githubusercontent.com/67836164/91966364-078b8600-ed12-11ea-8c11-e149b3872ea8.png)
![Öffnen der App _ Einstieg ](https://user-images.githubusercontent.com/67836164/91966366-078b8600-ed12-11ea-9049-11d378222a04.png)
![Suche](https://user-images.githubusercontent.com/67836164/91966368-078b8600-ed12-11ea-885f-8fa3f26d630c.png)
